# https://github.com/drduh/config/blob/master/user.action
# https://www.privoxy.org/user-manual/actions-file.html
# http://config.privoxy.org/show-url-info
{{ alias }}
+crunch-all-cookies = +crunch-incoming-cookies +crunch-outgoing-cookies
-crunch-all-cookies = -crunch-incoming-cookies -crunch-outgoing-cookies
allow-all-cookies   = -crunch-all-cookies -session-cookies-only -filter{content-cookies}
allow-popups        = -filter{all-popups} -filter{unsolicited-popups}
+block-as-image     = +block{Blocked image request.} +handle-as-image
-block-as-image     = -block
fragile             = -block -crunch-all-cookies -filter -fast-redirects -hide-referer -prevent-compression
{ fragile }
connectivitycheck.gstatic.com/generate_204
www.google.com/gen_204
.ubuntu.com
{ +block{html} }
/(.*/)adhandler/
/(.*/)partnerads.*.js
/(aff|adx|scrollad).php
/.*adEvents.*
/.*adimage*/*
/.*ads.js
/.*ads/.*
/.*adserver/*
/.*adtech.*
/.*advert.js.*
/.*advtcontent*/*
/.*affiliate/
/.*analytics.js.*
/.*banner*/*
/.*email=.*
/.*facebook.*
/.*fb.js.*
/.*linkedin.*
/.*php?stats.*
/.*rate.php
/.*shareBar.js
/.*smartads.*
/.*sponsor*/*
/.*track/ping.*
/.*tracking.*.js.*
/.adserv/
/?wordfence_logHuman.*
/FloatingAd.*.js
/ad-loader.js.*
/ad.html
/adGallery.html
/adReload.html
/ad_index_.*
/adheader.*
/adhtml/.*
/adplayer/*
/adtest/*
/adunit.php.*
/advert*/*
/affiliate.js
/ajax/ligatus/*
/analytics/
/banner*.*
/beacon.*
/cms_media/module_adbanner/
/cnt.php.*
/connect.ashx.*
/displayads/
/extjs/smartad.*\.js
/gather.asp.*
/gfx/layer/*
/gujAd/
/log/webtracker
/metriweb.*
/track.*
/urldata.act.*
/vtrack/
ad.
adimg.
admonkey.
ads.
ads.*.co.*/
ads.*.com/
ads2.
adserver.
analytics.*.
emailtrk.*
log.pinterest.com
pixel.*
{ +block{image} +handle-as-image }
/.*1x1.*
/.*beacon.*
/.*buttons.js
/.*facebook.*
/.*fb-icon.*
/.*follow_us.*
/.*images/social.*
/.*linkedin.*
/.*loading.gif
/.*measure.gif
/.*myspace.*
/.*share-buttons.*
/.*share-this.*
/.*static/button.*
/.*tracking-pixel.*
/adv_banner_.*
/assets/social-.*
/banner.php
/btn_ad_.*
/cleardot.gif
/followus-buttons.*
/iframe/ad/.*
/iframe/ads/.*
/image/ad/.*
/images/ad/.*
/images/ads.*
/images/ads/.*
/images/adv.*
/images/banners/
/images/sponsored/.*
/images_ad/.*
/img.ads.*
/img/ad-.*
/img/ad_.*
/img/social.*
/imgad_.*
/socialicons.*
{+set-image-blocker{http://10.8.1.1/}}
/.*.[jpg|jpeg|gif|png|tif|tiff]$
{ +redirect{s@google.com/amp/s/@@} }
google.com/amp/s/.*
{ +redirect{s@http://@https://@} }
.0x0.st
.4are.com
.abc.net.au
.accuweather.com
.adobe.com
.ae.com
.aexp-static.com
.aftership.com
.akamaihd.net
.alternet.org
.amazon.com
.amazonaws.com
.amd.com
.americanbar.org
.americanexpress.com
.amsecusa.com
.android.com
.annualcreditreport.com
.answers.com
.anthropologie.com
.apache.org
.appimage.org
.apple.com
.appspot.com
.arcgis.com
.archive.is
.archive.org
.archlinux.org
.arduino.cc
.arstechnica.com
.askubuntu.com
.asus.com
.ati.com
.atlassian.com
.auspost.com.au
.auth0.com
.authorize.net
.autotrader.com
.awesomeopensource.com
.awsstatic.com
.azurestandard.com
.bankofamerica.com
.barrons.com
.bbc.co.uk
.bbc.com
.benjaminmoore.com
.bestbuy.com
.bhphoto.com
.bing.com
.bit.ly
.bitbucket.org
.bitchute.com
.blogblog.com
.blogger.com
.bloglovin.com
.blogspot.co.uk
.blogspot.com
.blu-ray.com
.bootc.net
.bootstrapcdn.com
.boum.org
.box.com
.box.net
.boxcloud.com
.britishcouncil.org
.buildkite.com
.byexamples.com
.ca.gov
.canadapost.ca
.canon.com
.cbc.ca
.cbsnews.com
.ccc.de
.cdc.gov
.cdninstagram.com
.cdnme.se
.cdnst.net
.celestrak.com
.chase.com
.chewy.com
.chromium.org
.chrono24.com
.cia.gov
.cisco.com
.cleverbot.com
.cloudflare.com
.cloudfront.net
.cnbc.com
.cnet.com
.cnn.com
.cnn.io
.colorado.gov
.colostate.edu
.comcast.net
.congress.gov
.coreboot.org
.cpb.gov
.craigslist.org
.creativecommons.org
.crt.sh
.crucial.com
.cryptographyengineering.com
.cryptomuseum.com
.cs.cornell.edu
.custhelp.com
.dailycaller.com
.db.tt
.dd-wrt.com
.debian-administration.org
.debian.net
.debianforum.de
.definitions.net
.delta.com
.dhs.gov
.digitalgov.gov
.dropbox.com
.dropboxatwork.com
.dropboxteam.com
.duckduckgo.com
.duosecurity.com
.ebay.com
.ebaystatic.com
.ecfr.gov
.economist.com
.edgekey.net
.editmysite.com
.edx.org
.eff.org
.emacswiki.org
.epicgames.com
.eso.org
.etsy.com
.etsystatic.com
.export.gov
.fastly.com
.fastly.net
.fbi.gov
.fbinaa.org
.fda.gov
.fedex.com
.ffmpeg.org
.fidelity.com
.finviz.com
.flicker.com
.flickr.com
.flickr.net
.flightradar24.com
.foreignpolicy.com
.ftc.gov
.garmin.com
.generac.com
.gentoo.org
.gfycat.com
.ggpht.com
.gimp.org
.giphy.com
.github.com
.github.io
.githubapp.com
.githubassets.com
.githubusercontent.com
.gitlab.com
.gitlab.io
.gizmodo.com
.gmail.com
.gnu.org
.gnupg.org
.godoc.org
.gofundme.com
.gog-statics.com
.gog.com
.golang.com
.golang.org
.goo.gl
.google.ca
.google.co.uk
.google.com
.google.de
.google.net
.googleapis.com
.googleblog.com
.googlecode.com
.googlemail.com
.googlesource.com
.googleusercontent.com
.googlevideo.com
.governmentattic.org
.gravatar.com
.greenhouse.io
.gstatic.com
.gvt1.com
.gvt2.com
.gvt3.com
.hashicorp.com
.haxx.se
.hbr.org
.hireright.com
.homedepot.com
.homefinity.com
.hostux.net
.house.gov
.houzz.com
.hps.org
.hulu.com
.iana.org
.ibm.com
.icanhazip.com
.icann.org
.ietf.org
.ign.com
.ihouseelite.com
.images-amazon.com
.imageshack.com
.imageshack.us
.imdb.com
.imgbox.com
.imgur.com
.independent.ie
.indiegogo.com
.instagram.com
.intel.com
.intuit.com
.irs.gov
.isc.org
.ixquick.com
.jhu.edu
.jobvite.com
.jquery.com
.jsononline.com
.jstor.org
.justice.gov
.jwplatform.com
.kde.org
.kernel.org
.keybase.io
.khanacademy.org
.knowyourmeme.com
.landrover.com
.last.fm
.latimes.com
.lenovo.com
.letsencrypt.org
.levels.fyi
.lexus.com
.lighttpd.net
.linuxforums.org
.list-manage.com
.litmos.com
.lkml.org
.llvm.org
.loc.gov
.logicalincrements.com
.lowes.com
.lucid.co
.lush.com
.lwn.net
.mail-archive.com
.mapquest.com
.marc.info
.marketwatch.com
.marriott.com
.marshalls.com
.mathoverflow.com
.matrix.org
.media.tumblr.com
.medium.com
.meetup.com
.metafilter.com
.minus.com
.mit.edu
.morganstanley.com
.mozaws.net
.mozilla.net
.mozilla.org
.mozillazine.org
.msi.com
.muckrack.com
.namecheap.com
.nasa.gov
.nationalreview.com
.nbcuni.com
.ncbi.nlm.nih.gov
.netdna-ssl.com
.netflix.com
.newegg.com
.neweggimages.com
.nflxext.com
.nih.gov
.noaa.gov
.npr.org
.nsf.gov
.nxlfimg.net
.nypost.com
.nytimes.com
.okta.com
.oktacdn.com
.oneplus.com
.opencensus.io
.openh264.org
.openra.net
.openstreetmap.org
.openvpn.net
.openvpn.org
.optionstrat.com
.optoutprescreen.com
.overstock.com
.ovh.com
.ovh.net
.ovh.us
.parallels.com
.paypal.com
.pcengines.ch
.pcpartpicker.com
.petfinder.com
.phoronix.com
.photobucket.com
.phys.org
.phys.uwm.edu
.pinboard.in
.pinimg.com
.pinterest.com
.plos.org
.plosone.org
.popular.pics
.porscheusa.com
.potterybarn.com
.princeton.edu
.purpleair.com
.python.org
.pythonhosted.org
.quora.com
.quoracdn.net
.qz.com
.radioreference.com
.reason.com
.recaptcha.net
.recurve.com
.redd.it
.reddit.com
.redditmedia.com
.redditstatic.com
.reddituploads.com
.redfin.com
.redhat.com
.rei.com
.rentalcars.com
.reolink.com
.republicoftea.com
.researchgate.net
.reuters.com
.rolex.com
.rottentomatoes.com
.rust-lang.org
.salesforce.com
.samsung.com
.scene7.com
.schwab.com
.sciencemag.org
.scribd.com
.scribdassets.com
.sec.gov
.sec.report
.senate.gov
.serverfault.com
.shipstation.com
.shodan.io
.shopify.com
.signal.org
.singleapi.com
.singleplatform.com
.slack-edge.com
.slack-imgs.com
.slack.com
.slideshare.net
.smapi.io
.smh.com.au
.soundcloud.com
.sourceforge.net
.spacetelescope.org
.spaceweather.com
.spacex.com
.sparkpostmail.com
.splunk.com
.squarespace-cdn.com
.squarespace.com
.sstatic.net
.stackauth.com
.stackexchange.com
.stackoverflow.com
.startpage.com
.state.gov
.staticflickr.com
.steamcommunity.com
.steampowered.com
.steamstatic.com
.streamable.com
.suckless.org
.superuser.com
.swappa.com
.symantec.com
.t.co
.tableau.com
.tableausoftware.com
.target.com
.tastyworks.com
.taxfoundation.org
.teamspeak.com
.techdirt.com
.teddit.net
.theguardian.com
.thehill.com
.thehomedepot.com
.theverge.com
.thinkprogress.org
.thunderbird.net
.timex.com
.tomshardware.com
.tonic.to
.torproject.org
.toyota.com
.tractorsupply.com
.tradingview.com
.tripadvisor.com
.trulia.com
.trumba.com
.tumblr.com
.turbotax.com
.twimg.com
.twitch.tv
.twitter.com
.typepad.com
.ubuntuforums.org
.uhaul.com
.ui.com
.undeadly.org
.unicef.org
.ups.com
.urbanoutfitters.com
.usatoday.com
.usembassy.gov
.usgs.gov
.usps.com
.utah.gov
.vanguard.com
.verizon.com
.verizonwireless.com
.vice.com
.videolan.org
.vimeo.com
.vimeocdn.com
.vine.co
.virustotal.com
.vsco.co
.w.org
.w1.fi
.w3.org
.walgreens.com
.walmart.com
.walmartimages.com
.washingtonpost.com
.wayfair.com
.weather.gov
.wellsfargo.com
.westmarine.com
.whispersystems.org
.whitehouse.gov
.wikibooks.org
.wikimedia.org
.wikipedia.org
.wikiquote.org
.wiktionary.org
.windows.net
.wired.com
.wireshark.org
.wix.com
.wiz.io
.wmflabs.org
.woot.com
.wordpress.com
.wordpress.org
.wp.com
.wp.org
.wsj.com
.xfinity.com
.yahoo.com
.yahoo.net
.yahooapis.com
.ycombinator.com
.yelpcdn.com
.youtu.be
.youtube-dl.org
.youtube-nocookie.com
.youtube.com
.ytimg.com
.yubico.com
.zappos.com
.zendesk.com
.zillow.com
.zillowstatic.com
.zlcdn.com
.zoom.us
accounts.google.com
calendar.google.com
cdn.openbsd.org
cvsweb.openbsd.org
docs.google.com
drive.google.com
ftp.openbsd.org
mail.google.com
man.openbsd.org
maps.google.com
meet.google.com
photos.google.com
voice.google.com
wiki.debian.org
www.debian.org
www.google.com
www.openbsd.org
{ -redirect{android} }
connectivitycheck.gstatic.com/generate_204
#{+hide-user-agent{Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36}}
#{+hide-user-agent{Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36}}
#/
