# https://github.com/drduh/config/blob/main/privoxy/user.action
# https://www.privoxy.org/user-manual/actions-file.html
# http://config.privoxy.org/show-url-info
{{alias}}
upgrade = -block +redirect{s@http://@https://@}
unblock = -block -redirect

#{ +block{all} }
#/  # block all requests

{ +block{social} }
.discord.
.disqus.
.gravatar.
.licdn.
.linkedin.
.myspace.
.tiktok.
.tiktokcdn.
.twimg.
.twitter.
.twttr.
.x.

{ +block{facebook} }
.cdninstagram.
.facebook*.
.fb.
.fbstatic*.
.instagr.am
.fbcdn*.
.fbinfra.
.fbsbx.
.fbsv.
.fburl.
.tfbnw.
.thefacebook.
fb*.akamaihd.net

{ +block{ads and trackers} }
.google-analytics.
ad.
adnxs.
adsrv.
ads.
analytics.
appdynamics.
banner.
banners.
beacon.
click.
clickmeter.
count.
counter.
creatives.
location.
metric.
metrics.
mmetrics.
oas.
oascentral.
pixel.
seal.
seals.
smartadserver.
smetrics.
stats.
tag.
telemetry.
track.
tracker.
tracking.
trk.

{ upgrade{tlds} }
#.com
#.net
#.org
#.edu
#.ai
#.co.uk
#.org.uk
#.ac.jp
#.ac.uk
#.co
#.dev
#.fyi
#.gg
#.info
#.io
#.mil
#.tech
#.us

{ upgrade{patterns} }
#.*air.com
#.*api.com
#.*cdn.com
#.*cdn.net
#.*cloud.com
#.*contenthub.com
#.*flights.com
#.*img.com
#.*media.com
#.*news.com
#.*static.com
#.*wiki.com
#.akadns.net
#.akadns88.net
#.akam.net
#.akamai.com
#.akamai.net
#.akamaiedge.net
#.akamaihd.net
#.akamaitech.net
#.akamaized.net
#.awswaf.com
#.azure.
#.azureedge.net
#.bootstrapcdn.com
#.cloudflare.
#.cloudfront.net
#.cloudinary.com
#.datatables.net
#.edgekey.net
#.edgesuite.net
#.fastly.com
#.fastly.net
#.fastlydns.net
#.jsdelivr.net
#.mywebsitebuilder.com
#.salesforce-sites.com
#.shop.app
#.shopify.com
#.shopifyapps.com
#.shopifycdn.
#.shopifycs.com
#.shopifysvc.com
#.static.pub
#.statically.io
#.website-files.com
#api.
#assets*.
#blog.
#book.
#cdn.
#cdnjs.
#community.
#content.
#docs.
#documentation.
#download.
#form.
#forum*.
#git.
#gitlab.
#images.
#js.
#mirror*.
#order.
#pages.dev  # Cloudflare Pages
#pay.
#pictures.
#places.
#ppa.
#services.
#shop.
#static.
#store.
#support.
#wiki.

{ upgrade{everything else} }
.0x0.st
.3m.com
.aaplimg.com
.acm.org
.adafruit.com
.adblockplus.org
.adtidy.org
.ae.com
.aexp-static.com
.aexp.com
.aftership.com
.algolia.
.alienvault.com
.alpinelinux.org
.alternet.org
.amazon.com
.amazonaws.com
.amd.com
.americanbar.org
.americanexpress.com
.amiunique.org
.amsat.org
.amsecusa.com
.amzn.to
.anaconda.com
.anaconda.org
.android.com
.annualcreditreport.com
.ap.org
.apache.org
.apc.com
.appimage.org
.apple.com
.arcgis.com
.arcgisonline.com
.archive.is
.archive.org
.archive.ph
.archlinux.org
.arduino.cc
.arm.com
.arrl.org
.arstechnica.com
.arstechnica.net
.arubanetworks.com
.arxiv.org
.askubuntu.com
.asrock.com
.asus.com
.atl-paas.net  # atlassian
.atlassian.com
.atlassian.net
.auspost.com.au
.auth0.com
.authorize.net
.autocheck.com
.autotrader.com
.awesomeopensource.com
.awsstatic.com
.azureedge.net
.azurestandard.com
.badssl.com
.bankofamerica.com
.barrons.com
.basher.it
.bbc.co.uk
.bbc.com
.bbystatic.com
.beamng.com
.benjaminmoore.com
.benq.com
.bestbuy.com
.bhphoto.com
.bhphotovideo.com
.bigcommerce.com
.binarydefense.com
.bitbucket.org
.blackhat.com
.bleepingcomputer.com
.bleepstatic.com
.blogblog.com
.blogger.com
.bloglovin.com
.blogspot.
.blu-ray.com
.bmj.com
.bootc.net
.boum.org
.box.com
.box.net
.boxcdn.net
.boxcloud.com
.brew.sh
.bringatrailer.com
.broadcom.com
.brother-usa.com
.bsigroup.com
.buildkite.com
.businesswire.com
.byexamples.com
.bytebucket.org
.ca.gov
.canadapost.ca
.canarytokens.org
.canon.com
.canonical.com
.cbc.ca
.ccc.de
.cdc.gov
.cdn-apple.com
.cdn-redfin.com
.celestrak.com
.centos.org
.chase.com
.chatgpt.com
.chewy.com
.chromium.org
.chrono24.com
.cia.gov
.cisco.com
.cisecurity.org
.citizenlab.ca
.cloudflarestorage.com
.cloudfront.net
.cnet.com
.codeberg.org
.codecov.io
.coderpad.io
.colorado.gov
.colostate.edu
.comcast.net
.congress.gov
.coreboot.org
.cornell.edu
.cpb.gov
.cpubenchmark.net
.craigslist.org
.creativecommons.org
.crowdsupply.com
.crt.sh
.crucial.com
.cryptography.io
.cryptographyengineering.com
.cryptomuseum.com
.cs.cornell.edu
.ctfassets.net
.ctftime.org
.custhelp.com
.cve.org
.cvedetails.com
.cypherpunks.ca
.darkreading.com
.db.tt
.dd-wrt.com
.debian-administration.org
.debian.net
.debianforum.de
.dell.com
.dev.to
.dhs.gov
.die.net
.digicert.com
.digikey.com
.digitalgov.gov
.digitalocean.com
.discourse-cdn.com
.distrowatch.com
.docker.com
.docker.io
.documentcloud.org
.docusign.com
.doi.org
.dropbox.com
.dropboxatwork.com
.dropboxteam.com
.duo.com
.duosecurity.com
.ebay.com
.ebaycdn.net
.ebaydesc.com
.ebayimg.com
.ebayrtm.com
.ebaystatic.com
.ecfr.gov
.editmysite.com
.edx-cdn.org
.edx.org
.eff.org
.ehi.com
.emacswiki.org
.emergingthreats.net
.enterprise.com
.eoportal.org
.epicgames.com
.eso.org
.etrade.
.etsy.com
.etsystatic.com
.expedia.com
.export.gov
.fanboy.co.nz
.fandom.com
.fbi.gov
.fbinaa.org
.fccid.io
.fda.gov
.fedex.com
.fedoraproject.org
.ffmpeg.org
.fidelity.com
.finviz.com
.flathub.org
.flatpak.org
.flicker.com
.flickr.com
.flickr.net
.flightradar24.com
.forbes.com
.freebsd.org
.freebsdfoundation.org
.freedesktop.org
.freedomhouse.org
.freelists.org
.fsdn.com  # sourceforge
.fsf.org
.ftc.gov
.fwupd.org
.garmin.com
.geeqie.org
.gentoo.org
.gfycat.com
.ggpht.com
.ghcr.io
.gimp.org
.giphy.com
.github.blog
.github.com
.github.io
.githubapp.com
.githubassets.com
.githubusercontent.com
.gitlab.com
.gitlab.io
.gizmodo.com
.gmail.com
.gnome.org
.gnu.org
.gnupg.net
.gnupg.org
.go.dev
.godoc.org
.gofundme.com
.gog-statics.com
.gog.com
.golang.com
.golang.org
.goo.gl
.google
.google.
.googleapis.com
.googleblog.com
.googlecode.com
.googlemail.com
.googlesource.com
.googleusercontent.com
.googlevideo.com
.governmentattic.org
.gparted.org
.grapheneos.org
.greenhouse.io
.gstatic.com
.guim.co.uk
.gvt0.com
.gvt1.com
.gvt2.com
.gvt3.com
.happycow.net
.hashicorp.com
.haxx.se
.hbr.org
.he.net
.hf.co
.hf.space
.hireright.com
.homedepot.com
.house.gov
.houzz.com
.hps.org
.huggingface.co
.hybrid-analysis.com
.iacr.org
.iana.org
.ibm.com
.icanhazip.com
.icann.org
.icannwiki.org
.ietf.org
.ifixit.com
.ign.com
.images-amazon.com
.imdb.com
.imfreedom.org
.imgbox.com
.imgix.net
.imgur.com
.intel.com
.invidious.io
.ipdeny.com
.irs.gov
.isc.org
.itsfoss.com
.ixquick.com
.jhu.edu
.jobvite.com
.jquery.com
.jsononline.com
.jstor.org
.justdeleteme.xyz
.justice.gov
.jwplatform.com
.kde.org
.kdenlive.org
.kernel.org
.keybase.io
.keylength.com
.khanacademy.org
.kiwix.org
.knowyourmeme.com
.kubernetes.io
.last.fm
.launchpad.net
.lenovo.com
.letsencrypt.org
.levels.fyi
.lever.co
.lexus.com
.lg.com
.libreoffice.org
.libssh.org
.lighttpd.net
.lineageos.com
.lineageos.org
.linux-audit.com
.linuxforums.org
.linuxjournal.com
.linuxquestions.org
.list-manage.com
.litmos.com
.lkml.org
.llvm.org
.loc.gov
.logicalincrements.com
.lots-project.com
.lucid.co
.lutris.net
.lwn.net
.lww.com
.macmillan.com
.mail-archive.com
.mailbox.org
.mamba.pm
.manjaro.org
.mapquest.com
.marc.info
.marketwatch.com
.mastodon.social
.mastodon.world
.mathopolis.com
.mathoverflow.com
.mathsisfun.com
.matrix.org
.matterport.com
.media-amazon.com
.medium.com
.meetup.com
.meetupstatic.com
.metafilter.com
.mit.edu
.mitre.org
.morganstanley.com
.mozaws.net
.mozilla.net
.mozilla.org
.mozillazine.org
.mqcdn.com  # mapquest
.msi.com
.muckrack.com
.muckrock.com
.mwl.io
.namecheap.com
.nasa.gov
.nc-img.com
.netdna-ssl.com
.netify.ai
.newegg.com
.neweggimages.com
.nextdoor.com
.nexusmods.com
.nginx.org
.nh.us
.nih.gov
.nixos.org
.noaa.gov
.nodejs.org
.nordstrom.com
.noscript.net
.npr.org
.nro.net
.nsf.gov
.nvidia.com
.nypost.com
.nyt.com
.nytimes.com
.octocaptcha.com
.okstate.edu
.okta.com
.oktacdn.com
.ollama.com
.oneplus.com
.onerng.info
.openai.com
.opencensus.io
.openra.net
.openshot.org
.openssl.org
.openstreetmap.org
.opensuse.org
.openvpn.net
.openvpn.org
.openwall.com
.openwebui.com
.opnsense.org
.optionstrat.com
.optoutprescreen.com
.ovh.com
.ovh.net
.ovh.us
.owasp.org
.pages.dev
.pandoc.org
.parallels.com
.pastebin.com
.patreon.com
.patreonusercontent.com
.pcengines.ch
.pcmag.com
.pcpartpicker.com
.petfinder.com
.pewresearch.org
.pfsense.org
.phoronix.com
.phoronix.net
.phys.org
.pi-hole.net
.pinboard.in
.pinimg.com
.pinterest.
.plos.org
.plosone.org
.podman.io
.popular.pics
.posteo.de
.princeton.edu
.privacyguides.org
.privoxy.org
.propublica.org
.proton.me
.publicsuffix.org
.purpleair.com
.pypi.org
.python.org
.pythonhosted.org
.pytorch.org
.quad9.net
.qubes-os.org
.qz.com
.radb.net
.radeon.com
.radioreference.com
.raspberrypi.com
.raspberrypi.org
.readthedocs.io
.recaptcha.net
.redd.it
.reddit.com
.redditmedia.com
.redditstatic.com
.reddituploads.com
.redfin.com
.redhat.com
.rei.com
.rentalcars.com
.reolink.com
.reolink.us
.republicoftea.com
.researchgate.net
.reshade.me
.reuters.com
.ripe.net
.riseup.net
.rottentomatoes.com
.rtings.com
.rubygems.org
.rust-lang.org
.rustup.rs
.sagepub.com
.samsung.com
.sans.edu
.sans.org
.satnogs.org
.schwab.com
.sciencedirect.com
.scotusblog.com
.scribd.com
.scribdassets.com
.sec.gov
.sec.report
.securelist.com
.senate.gov
.serverfault.com
.shellcheck.net
.shipstation.com
.shodan.io
.signal.org
.singleplatform.com
.slack-edge.com
.slack-imgs.com
.slack.com
.slideshare.net
.smallstep.com
.smapi.io
.snapcraft.io
.someonewhocares.org
.soundcloud.com
.sourceforge.io
.sourceforge.net
.space.com
.spacetelescope.org
.spaceweather.com
.spaceweathergallery2.com
.spacex.com
.sparkfun.com
.splunk.com
.squarespace-cdn.com
.squarespace.com
.ssl-images-amazon.com
.ssllabs.com
.sstatic.net
.stackauth.com
.stackexchange.com
.stackoverflow.com
.startpage.com
.state.gov
.static-bluray.com
.static.pub
.staticflickr.com
.statuspage.io
.steamcommunity.com
.steamcontent.com  # streams
.steamdb.info
.steamdeck.com
.steamgames.com
.steamos.cloud
.steampowered.com
.steamserver.net
.steamstatic.com
.stlouisfed.org
.streamable.com
.stunnel.org
.suckless.org
.superuser.com
.suse.com
.swappa.com
.sweetwater.com
.sysctl-explorer.net
.tableau.com
.tableausoftware.com
.tacdn.com  # tripadvisor
.target.com
.targetimg1.com
.taxfoundation.org
.techradar.com
.terraform.io
.thdstatic.com
.theguardian.com
.thehomedepot.com
.theverge.com
.threatpost.com
.thunderbird.net
.time.gov
.tldp.org
.tomshardware.com
.tonic.to
.torproject.org
.toyota.com
.tractorsupply.com
.tradingview.com
.travel-assets.com
.tripadvisor.com
.trmm.net
.tuta.com
.twitch.tv
.ubuntuforums.org
.ubuntuhandbook.org
.uefi.org
.ui.com
.umu.se
.undeadly.org
.unicef.org
.unix.com
.unsplash.com
.ups.com
.usembassy.gov
.userbenchmark.com
.usgs.gov
.usps.com
.utah.gov
.vanguard.com
.verizon.com
.verizonwireless.com
.vermont.gov
.vgcontent.info
.vgdynamic.info
.videolan.org
.vimeo.com
.vimeocdn.com
.virustotal.com
.vmware.com
.voidlinux.org
.vt.edu
.w.org
.w1.fi
.w3.org
.w3schools.com
.walmart.com
.walmartimages.com
.weather.gov
.whispersystems.org
.whitehouse.gov
.whois.com
.whonix.org
.wikibooks.org
.wikidata.org
.wikimedia.org
.wikimediafoundation.org
.wikinews.org
.wikipedia.org
.wikiquote.org
.wikisource.org
.wikiversity.org
.wikivoyage.org
.wiktionary.org
.wiley.com
.wired.com
.wireshark.org
.wix.com
.wixsite.com
.wiz.io
.wordpress.com
.wordpress.org
.wp.com
.wp.org
.xcp-ng.org
.xda-developers.com
.xfinity.com
.xfree86.org
.xmpp.org
.xubuntu.org
.yahoo.
.yahooapis.com
.ycombinator.com
.yelp.com
.yelpcdn.com
.yimg.com  # yahoo
.youtu.be
.youtube-dl.org
.youtube-nocookie.com
.youtube.com
.yoyo.org
.ytimg.com
.yubico.com
.zdassets.com  # zendesk
.zdnet.com
.zendesk.com
.zoom.us
.zoominfo.com
accounts.google.com
calendar.google.com
cdimage.debian.org
cdn.openbsd.org
cdnjs.cloudflare.com
challenges.cloudflare.com  # cloudflare captcha
cr.yp.to
cvsweb.openbsd.org
debian.org
developer.chrome.com
docs.google.com
drive.google.com
ftp.openbsd.org
libreddit.
lists.debian.org
mail.google.com
man.openbsd.org
maps.google.com
meet.google.com
openbsd.org
photos.google.com
release.debian.org
security-tracker.debian.org
steamuserimages-a.akamaihd.net
voice.google.com
wiki.debian.org
www.debian.org
www.google.com
www.openbsd.org

{ unblock{local} }
#127.0.0.1:8080
#localhost:8080
127.0.0.1
10.0.
172.16.
192.168.

{ unblock{infra} }
.amazontrust.com
.arpa
.example.com
.gov
.lencr.org
.openh264.org
.pki.goog
.ss2.us
.ubuntu.com
cacerts.
crl.
myspeed.
ntp.org
ocsp.
status.rapidssl.com
status.thawte.com
zerossl.ocsp.sectigo.com

{ unblock{speedtest} }
.speedtest.net
speedtest.
myspeed.

{ unblock{steam} }
ping.archlinux.org/nm-check.txt
test.steampowered.com/204

{ unblock{android} }
connectivitycheck.gstatic.com/generate_204

#{+hide-user-agent{Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36}}
#/

#{+set-image-blocker{http://10.8.1.1/}}
#/.*.[jpg|jpeg|gif|png|webp]$
