# https://github.com/drduh/config/blob/master/privoxy/user.action
# https://www.privoxy.org/user-manual/actions-file.html
# http://config.privoxy.org/show-url-info

#{ +block{all} }
#.

{ +block{facebook} }
.facebook*.
.fb.
.fbcdn*.
.fbinfra.
.fbsbx.
.fbsv.
.tfbnw.
.thefacebook.
fb*.akamaihd.net

{ +block{ads} }
ad.
adnxs.
ads.
analytics.
appdynamics.
banner.
banners.
beacon.
click.
clickmeter.
count.
counter.
creatives.
metric.
metrics.
mmetrics.
oas.
oascentral.
pixel.
smartadserver.
smetrics.
stats.
tag.
telemetry.
track.
tracker.
tracking.
trk.

{ -block }
10.0.
172.16.
192.168.
.amazontrust.com
.arpa
.gov
.lencr.org
ntp.org
ocsp.
pki.goog
.ubuntu.com

{ -block +redirect{s@http://@https://@} }
#.com
#.net
#.org
#.edu
#.ai
#.dev
#.fyi
#.gg
#.info
#.io
#.mil
#.tech
#.us
.*cdn.com
.*media.com
.*news.com
.*wiki.com
.0x0.st
.4are.com
.aaplimg.com
.abc.net.au
.ac.jp
.ac.uk
.accuweather.com
.acm.org
.adblockplus.org
.adobe.com
.ae.com
.aexp-static.com
.aftership.com
.akadns.net
.akadns88.net
.akamai.com
.akamai.net
.akamaiedge.net
.akamaihd.net
.akamaitech.net
.akamaized.net
.algolia.
.alternet.org
.amazon.com
.amazonaws.com
.amd.com
.americanbar.org
.americanexpress.com
.amiunique.org
.amsecusa.com
.android.com
.annualcreditreport.com
.answers.com
.anthropologie.com
.ap.org
.apache.org
.appimage.org
.apple.com
.appspot.com
.arcgis.com
.archive.is
.archive.org
.archlinux.org
.arduino.cc
.arstechnica.com
.arxiv.org
.askubuntu.com
.asus.com
.ati.com
.atlassian.com
.auspost.com.au
.auth0.com
.authorize.net
.autotrader.com
.awesomeopensource.com
.awsstatic.com
.azurestandard.com
.bankofamerica.com
.barrons.com
.bbc.co.uk
.bbc.com
.benjaminmoore.com
.bestbuy.com
.bhphoto.com
.bing.com
.bit.ly
.bitbucket.org
.bitchute.com
.blogblog.com
.blogger.com
.bloglovin.com
.blogspot.
.blu-ray.com
.bootc.net
.bootstrapcdn.com
.boum.org
.box.com
.box.net
.boxcloud.com
.britishcouncil.org
.buildkite.com
.byexamples.com
.ca.gov
.canadapost.ca
.canon.com
.cbc.ca
.ccc.de
.cdc.gov
.cdn-apple.com
.cdninstagram.com
.cdnme.se
.cdnst.net
.celestrak.com
.chase.com
.chewy.com
.chromium.org
.chrono24.com
.cia.gov
.cisco.com
.cleverbot.com
.cloudflare.
.cloudfront.net
.cnbc.com
.cnet.com
.cnn.com
.cnn.io
.codeberg.org
.colorado.gov
.colostate.edu
.comcast.net
.congress.gov
.coreboot.org
.cpb.gov
.craigslist.org
.creativecommons.org
.crt.sh
.crucial.com
.cryptographyengineering.com
.cryptomuseum.com
.cs.cornell.edu
.ctfassets.net
.custhelp.com
.dailycaller.com
.db.tt
.dd-wrt.com
.debian-administration.org
.debian.net
.debianforum.de
.definitions.net
.delta.com
.dhs.gov
.digitalgov.gov
.doi.org
.dropbox.com
.dropboxatwork.com
.dropboxteam.com
.duckduckgo.com
.duosecurity.com
.ebay.com
.ebaycdn.net
.ebaydesc.com
.ebayimg.com
.ebayrtm.com
.ebaystatic.com
.ecfr.gov
.economist.com
.edgekey.net
.edgesuite.net
.editmysite.com
.edx.org
.eff.org
.emacswiki.org
.epicgames.com
.eso.org
.etsy.com
.etsystatic.com
.expedia.com
.export.gov
.fandom.com
.fastly.com
.fastly.net
.fastlydns.net
.fbi.gov
.fbinaa.org
.fda.gov
.fedex.com
.ffmpeg.org
.fidelity.com
.finviz.com
.flicker.com
.flickr.com
.flickr.net
.flightradar24.com
.foreignpolicy.com
.freebsd.org
.ftc.gov
.garmin.com
.generac.com
.gentoo.org
.gfycat.com
.ggpht.com
.gimp.org
.giphy.com
.github.com
.github.io
.githubapp.com
.githubassets.com
.githubusercontent.com
.gitlab.com
.gitlab.io
.gizmodo.com
.gmail.com
.gnu.org
.gnupg.org
.godoc.org
.gofundme.com
.gog-statics.com
.gog.com
.golang.com
.golang.org
.goo.gl
.google.
.googleapis.com
.googleblog.com
.googlecode.com
.googlemail.com
.googlesource.com
.googleusercontent.com
.googlevideo.com
.governmentattic.org
.gravatar.com
.greenhouse.io
.gstatic.com
.guim.co.uk
.gvt0.com
.gvt1.com
.gvt2.com
.gvt3.com
.hashicorp.com
.haxx.se
.hbr.org
.he.net
.hireright.com
.homedepot.com
.homefinity.com
.hostux.net
.house.gov
.houzz.com
.hps.org
.hulu.com
.iana.org
.ibm.com
.icanhazip.com
.icann.org
.icannwiki.org
.ietf.org
.ign.com
.ihouseelite.com
.images-amazon.com
.imageshack.com
.imageshack.us
.imdb.com
.imgbox.com
.imgur.com
.independent.ie
.indiegogo.com
.instagram.com
.intel.com
.intuit.com
.invidious.io
.irs.gov
.isc.org
.ixquick.com
.jhu.edu
.jobvite.com
.jquery.com
.jsononline.com
.jstor.org
.justice.gov
.jwplatform.com
.kde.org
.kernel.org
.keybase.io
.khanacademy.org
.knowyourmeme.com
.landrover.com
.last.fm
.latimes.com
.lenovo.com
.letsencrypt.org
.levels.fyi
.lever.co
.lexus.com
.lg.com
.lighttpd.net
.linuxforums.org
.linuxjournal.com
.list-manage.com
.litmos.com
.lkml.org
.llvm.org
.loc.gov
.logicalincrements.com
.lowes.com
.lucid.co
.lush.com
.lwn.net
.mail-archive.com
.mapquest.com
.marc.info
.marketwatch.com
.marriott.com
.marshalls.com
.mathoverflow.com
.matrix.org
.media-amazon.com
.media.tumblr.com
.medium.com
.meetup.com
.meetupstatic.com
.metafilter.com
.minus.com
.mit.edu
.morganstanley.com
.mozaws.net
.mozilla.net
.mozilla.org
.mozillazine.org
.mqcdn.com  # mapquest
.msi.com
.muckrack.com
.muckrock.com
.namecheap.com
.nasa.gov
.nationalreview.com
.nbcuni.com
.nc-img.com
.ncbi.nlm.nih.gov
.netdna-ssl.com
.netflix.com
.netify.ai
.newegg.com
.neweggimages.com
.nextdoor.com
.nflxext.com
.nh.us
.nih.gov
.noaa.gov
.nordstrom.com
.npr.org
.nro.net
.nsf.gov
.nxlfimg.net
.nypost.com
.nyt.com
.nytimes.com
.okta.com
.oktacdn.com
.oneplus.com
.opencensus.io
.openh264.org
.openra.net
.openstreetmap.org
.opensuse.org
.openvpn.net
.openvpn.org
.optimizely.com
.optionstrat.com
.optoutprescreen.com
.overstock.com
.ovh.com
.ovh.net
.ovh.us
.parallels.com
.patreon.com
.patreonusercontent.com
.paypal.com
.pcengines.ch
.pcpartpicker.com
.petfinder.com
.pewresearch.org
.phoronix.com
.photobucket.com
.phys.org
.pi-hole.net
.pinboard.in
.pinimg.com
.pinterest.
.plos.org
.plosone.org
.popular.pics
.porscheusa.com
.potterybarn.com
.princeton.edu
.privoxy.org
.purpleair.com
.python.org
.pythonhosted.org
.quora.com
.quoracdn.net
.qz.com
.radioreference.com
.reason.com
.recaptcha.net
.recurve.com
.redd.it
.reddit.com
.redditmedia.com
.redditstatic.com
.reddituploads.com
.redfin.com
.redhat.com
.rei.com
.rentalcars.com
.reolink.com
.reolink.us
.republicoftea.com
.researchgate.net
.reuters.com
.ripe.net
.rolex.com
.rottentomatoes.com
.rust-lang.org
.salesforce.com
.samsung.com
.scene7.com
.schwab.com
.sciencemag.org
.scotusblog.com
.scribd.com
.scribdassets.com
.sec.gov
.sec.report
.senate.gov
.serverfault.com
.shipstation.com
.shodan.io
.shop.app
.shopify.com
.shopifycdn.
.shopifycs.com
.shopifysvc.com
.signal.org
.singleapi.com
.singleplatform.com
.slack-edge.com
.slack-imgs.com
.slack.com
.slideshare.net
.smapi.io
.smh.com.au
.soundcloud.com
.sourceforge.io
.sourceforge.net
.spacetelescope.org
.spaceweather.com
.spacex.com
.sparkpostmail.com
.splunk.com
.squarespace-cdn.com
.squarespace.com
.ssl-images-amazon.com
.sstatic.net
.stackauth.com
.stackexchange.com
.stackoverflow.com
.startpage.com
.state.gov
.static-bluray.com
.staticflickr.com
.steamcommunity.com
.steamcontent.com  # streams
.steamdb.info
.steamgames.com
.steampowered.com
.steamserver.net
.steamstatic.com
.streamable.com
.suckless.org
.superuser.com
.swappa.com
.symantec.com
.t.co
.tableau.com
.tableausoftware.com
.tacdn.com  # tripadvisor
.target.com
.targetimg1.com
.tastyworks.com
.taxfoundation.org
.techdirt.com
.teddit.net
.thdstatic.com
.theguardian.com
.thehill.com
.thehomedepot.com
.thennowmovielocations.com
.theverge.com
.thinkprogress.org
.thunderbird.net
.time.gov
.timex.com
.tomshardware.com
.tonic.to
.torproject.org
.toyota.com
.tractorsupply.com
.tradingview.com
.travel-assets.com
.tripadvisor.com
.trulia.com
.trumba.com
.tumblr.com
.turbotax.com
.twimg.com
.twitch.tv
.twitter.com
.typepad.com
.ubuntuforums.org
.uhaul.com
.ui.com
.undeadly.org
.unicef.org
.ups.com
.urbanoutfitters.com
.usatoday.com
.usembassy.gov
.usgs.gov
.usps.com
.utah.gov
.vanguard.com
.verizon.com
.verizonwireless.com
.vermont.gov
.vice.com
.videolan.org
.vimeo.com
.vimeocdn.com
.vine.co
.virustotal.com
.vsco.co
.w.org
.w1.fi
.w3.org
.walgreens.com
.walmart.com
.walmartimages.com
.washingtonpost.com
.wayfair.com
.weather.gov
.wellsfargo.com
.westmarine.com
.whispersystems.org
.whitehouse.gov
.whois.com
.wikibooks.org
.wikimedia.org
.wikimediafoundation.org
.wikipedia.org
.wikiquote.org
.wiktionary.org
.windows.net
.wired.com
.wireshark.org
.wix.com
.wiz.io
.wmflabs.org
.woot.com
.wordpress.com
.wordpress.org
.wp.com
.wp.org
.wsj.com
.x.com
.xfinity.com
.yahoo.
.yahooapis.com
.ycombinator.com
.yelp.com
.yelpcdn.com
.youtu.be
.youtube-dl.org
.youtube-nocookie.com
.youtube.com
.ytimg.com
.yubico.com
.zappos.com
.zendesk.com
.zillow.com
.zillow.net
.zillowstatic.com
.zlcdn.com
.zoom.us
accounts.google.com
calendar.google.com
cdn.openbsd.org
cvsweb.openbsd.org
docs.google.com
drive.google.com
ftp.openbsd.org
libreddit.
mail.google.com
man.openbsd.org
maps.google.com
meet.google.com
photos.google.com
voice.google.com
wiki.debian.org
www.debian.org
www.google.com
www.openbsd.org

{ -redirect{android} }
connectivitycheck.gstatic.com/generate_204

#{+hide-user-agent{Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36}}
#{+hide-user-agent{Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36}}
#/

#{+set-image-blocker{http://10.8.1.1/}}
#/.*.[jpg|jpeg|gif|png|webp]$
