# https://github.com/drduh/config/blob/main/ntp.conf

# server config
# validate: sudo ntpq -pn ; sudo journalctl -u ntpsec -f
driftfile /var/lib/ntpsec/ntp.drift
leapfile /usr/share/zoneinfo/leap-seconds.list

# provide time even without upstream sources
tos orphan 8
tos minsane 3

# upstream sources
pool 0.north-america.pool.ntp.org iburst
server time.cloudflare.com iburst
server time.google.com iburst

# listen addresses
interface ignore wildcard
interface listen 172.31.255.225
interface listen 10.127.0.97
interface listen 10.19.18.1

# localhost
restrict 127.0.0.1
restrict ::1

# local clients
restrict 172.31.255.225 mask 255.255.255.224 nomodify noquery
restrict 10.127.0.97 mask 255.255.255.224 nomodify noquery
restrict 10.19.18.1 mask 255.255.255.224 nomodify noquery

restrict -4 default kod nomodify noquery limited
restrict -6 default kod nomodify noquery limited

# client config

server 172.31.255.225 iburst
server 10.127.0.97 iburst
server 10.19.18.1 iburst
restrict 127.0.0.1
restrict ::1
restrict default noquery nomodify
